### ISSUE TITLE
Allow setting strict_protocols in config files

### ISSUE THREAD

**Issue by irskep** [Yelp/mrjob#696] opened 2013-08-08 21:20 UTC
I can't think of a reason why this shouldn't be allowed.

I also think we should consider flipping the default to `True`. It's pretty user-hostile to silently discard data, which newbies are likely to generate.

**Comment by davidmarin** [comment] 2015-03-18 00:07
Duplicate of #726.

**Closed by davidmarin** 2015-03-18 00:07 UTC
Labels: Feature
