### ISSUE TITLE
Describe local-runner config

### ISSUE THREAD

**Issue by msiebuhr** [Yelp/mrjob#926] opened 2014-07-22 12:43 UTC
I find the local runner somewhat useful to easily run smaller jobs on my local machine, but I'm struggling a bit with getting the parallelization to work nicely.

By default it runs just two mapper and reducer processes. After some hours of digging around, I found out it could be set on the command line as:

    script.py -r local --jobconf mapred.map.tasks=8 --jobconf=mapred.reduce.tasks-8

I tried putting this in `~/.mrjob.conf`, which has caused it to start 100+ processes while running a job:

    runners:
        local:
            jobconf:
                mapred.map.tasks: "4"
                mapred.reduce.tasks: "4"

(It complains loudly if the numbers aren't encoded at strings.)

Bug-wise, I guess it comes down to:

 - Shouldn't it start $NUMCPU jobs by default?
 - Describe the parameters in the documentation

**Comment by davidmarin** [comment] 2015-03-11 00:17
Yes, it definitely should. Local mode is just a pain to modify and a low priority.

I think this is a duplicate of #280.

**Closed by davidmarin** 2015-03-11 00:17 UTC
Labels: Bug
