### ISSUE TITLE
UnboundLocalError: local variable 'task_error' referenced before assignment

### ISSUE THREAD

**Issue by jleclanche** [Yelp/mrjob#1456] opened 2016-10-11 11:41 UTC
I got the following traceback during a run:

```pytb
Traceback (most recent call last):
  File "./chess_brawl.py", line 182, in <module>
    Job.run()
  File "/home/adys/.local/share/virtualenvs/hs/lib/python3.5/site-packages/mrjob/job.py", line 429, in run
    mr_job.execute()
  File "/home/adys/.local/share/virtualenvs/hs/lib/python3.5/site-packages/mrjob/job.py", line 447, in execute
    super(MRJob, self).execute()
  File "/home/adys/.local/share/virtualenvs/hs/lib/python3.5/site-packages/mrjob/launch.py", line 158, in execute
    self.run_job()
  File "/home/adys/.local/share/virtualenvs/hs/lib/python3.5/site-packages/mrjob/launch.py", line 228, in run_job
    runner.run()
  File "/home/adys/.local/share/virtualenvs/hs/lib/python3.5/site-packages/mrjob/runner.py", line 481, in run
    self._run()
  File "/home/adys/.local/share/virtualenvs/hs/lib/python3.5/site-packages/mrjob/emr.py", line 945, in _run
    self._finish_run()
  File "/home/adys/.local/share/virtualenvs/hs/lib/python3.5/site-packages/mrjob/emr.py", line 950, in _finish_run
    self._wait_for_steps_to_complete()
  File "/home/adys/.local/share/virtualenvs/hs/lib/python3.5/site-packages/mrjob/emr.py", line 1845, in _wait_for_steps_to_complete
    self._wait_for_step_to_complete(step.id, step_num, num_steps)
  File "/home/adys/.local/share/virtualenvs/hs/lib/python3.5/site-packages/mrjob/emr.py", line 1968, in _wait_for_step_to_complete
    error = self._pick_error(log_interpretation)
  File "/home/adys/.local/share/virtualenvs/hs/lib/python3.5/site-packages/mrjob/logs/mixin.py", line 115, in _pick_error
    self._interpret_task_logs(log_interpretation)
  File "/home/adys/.local/share/virtualenvs/hs/lib/python3.5/site-packages/mrjob/logs/mixin.py", line 192, in _interpret_task_logs
    stderr_callback=_log_parsing_task_stderr)
  File "/home/adys/.local/share/virtualenvs/hs/lib/python3.5/site-packages/mrjob/logs/task.py", line 168, in _interpret_task_logs
    if partial and task_error:
UnboundLocalError: local variable 'task_error' referenced before assignment
```

Looking at the code in `_interpret_task_logs` (`mrjob/logs/task.py`), `task_error` is not unless `if fs.exists(stderr_path)` is true at least once. I can submit a PR.

**Comment by davidmarin** [comment] 2016-10-11 23:16
Thanks, will get to this on Friday. :)

**Comment by jleclanche** [comment] 2016-10-11 23:18
@davidmarin I filed a PR.

**Comment by davidmarin** [comment] 2016-10-14 18:10
I know! I need to write regression tests too.

In this case, it looks like the existing tests would have caught this, except that I forgot to patch in my mock `fs.exists()` method.

**Comment by davidmarin** [comment] 2016-10-14 18:14
Merged. Thanks!

**Closed** 2016-10-14 18:13 UTC
Labels: Bug
